### ISSUE TITLE
Exportify fails to Export Music Located in Local Files.

### ISSUE THREAD

**Issue by alchokem** [pavelkomarov/exportify#47]
Analyze the data [like this](http://pavelkomarov.com/exportify/taste_analysis) by [launching the notebook](https://mybinder.org/v2/gh/pavelkomarov/exportify/master), uploading your .csv, and running the .ipynb.

Couldn't export Mark Morrison with id 2B9xT4Ze6pVpWsgVnj4F1u. Encountered TypeError: Cannot read properties of undefined (reading 'forEach')
TypeError: Cannot read properties of undefined (reading 'forEach') at https://exportify.net/exportify.js:289:41 at Array.forEach () at https://exportify.net/exportify.js:289:9 at async Object.export (https://exportify.net/exportify.js:183:15)
Please [let us know](https://github.com/pavelkomarov/exportify/issues/10). The others are still being zipped.

Playlist: https://open.spotify.com/playlist/2B9xT4Ze6pVpWsgVnj4F1u.  Cause: open.spotify.com fails to access local files.

**Comment by pavelkomarov** [comment]
I think this should fix it https://github.com/pavelkomarov/exportify/commit/1b53b9543b6f9746c0bfb0a9ce72ad7d2f71a96d
